env:
  global:
    - CC_TEST_REPORTER_ID=4b5d2d514f7e24114d6cd3b79586ffb01e57c00d3bc166d90a8ab1d60513c8ed
language: 
  - node_js
node_js:
  - "8"
branches:
  except:
    - dev
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  - make lint
  - npm test -- --coverage
after_script:
  - ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $TRAVIS_TEST_RESULT
